### PR TITLE
Only use alphanumeric values for property names

### LINKED ISSUE #14: Special characteres issue
Hi,

In my localization file I have an string like this:
```
reset-pass-label = "Enter your email address below and we'll \r\n send you a new password";
```

I used ***\r\n*** because I need to break the line at that point, the problem is that the generated Swift file looks like this:

```
/// Base translation: Enter your email address below and we'll 
 send you a new password
    public static var ResetPassLabel : String = "reset-pass-label".localized
```
Somehow the break line is being applied to the source code as well, as a result the file does not compile.

### PR DESCRIPTION
**Pull request by BenchR267**
This should ensure that only alphanumeric values are used to create the properties of the generated class / struct. This should also fix #14

### CODE REVIEW

**Comment by JiriTrecak** [comment]
Hey,

#14 has nothing to do with this problem :) 14 is very specific comment issue where 

    /// comment \r comment 

goes to second line, which is not properly prefixed with /// as I want to keep comments 1-line for now.

As for your pull request: 
- guard is definitely good idea, safety is always good
- your second part of fix is too complicated (can be done by cycle, 6 lines of anything that is same is too much. It also assumes that you listed all characters, which you definitely did not (ěščřžýáí? :) 

Since you have the point though - it should be sanitized - lets make better solution - extend existing String extension with something like this:

    extension String {
        func alphanumericString() -> String {
            return self.stringByFoldingWithOptions(NSStringCompareOptions.DiacriticInsensitiveSearch, locale: NSLocale.currentLocale())
        }
    }


This should properly convert those special characters to their ascii counterparts (this does the same thing as yours, but natively). When you are done with it, lets test if it works. Also, please don't use "var" in method definition and instead use new property, as this won't work anymore in swift 3.0.

note: sorry if the code has typo, I wrote it on mobile.

Thanks!

**Comment by BenchR267** [comment]
Thanks for you comment, very good point! I reworked it and included also the NSCharacterSet stuff because also the special characters should be removed. Since you said guard is a good idea I brought some more safety to the generator by eliminating some forced type transformations ;)

**Comment by JiriTrecak** [comment]
Excellent. I will test it once I get home. Can you please make it so it is just one commit (rebase)?

Also just a side note, next time, please PR into /development - but it is okay for now.

**Comment by BenchR267** [comment]
lol, i messed it up. take a look later :)

**Pull request closed without merging**
